from __future__ import annotations

MOCK_GAMES = [
    {
        "id": -101,
        "title": "The Legend of Zelda: The Wind Waker",
        "platform_id": "gamecube",
        "platform": "Nintendo GameCube",
        "genres": "Adventure",
        "release_year": 2002,
        "description": "Mock design item. Replace by scanning your library.",
        "rom_path": "mock://wind-waker",
        "emulator_profile_id": "dolphin_gamecube",
        "cover_path": "DefaultProgram.png",
        "fanart_path": "",
        "logo_path": "",
        "favorite": 1,
        "last_played": "2099-01-01 00:00:00",
        "play_count": 3,
    },
    {
        "id": -102,
        "title": "Super Mario Sunshine",
        "platform_id": "gamecube",
        "platform": "Nintendo GameCube",
        "genres": "Platformer",
        "release_year": 2002,
        "description": "Mock design item. Replace by scanning your library.",
        "rom_path": "mock://sunshine",
        "emulator_profile_id": "dolphin_gamecube",
        "cover_path": "DefaultProgram.png",
        "fanart_path": "",
        "logo_path": "",
        "favorite": 0,
        "last_played": "2099-01-02 00:00:00",
        "play_count": 2,
    },
    {
        "id": -201,
        "title": "Metroid Fusion",
        "platform_id": "gba",
        "platform": "Game Boy Advance",
        "genres": "Adventure",
        "release_year": 2002,
        "description": "Mock design item. Replace by scanning your library.",
        "rom_path": "mock://metroid-fusion",
        "emulator_profile_id": "mgba_gba",
        "cover_path": "DefaultProgram.png",
        "fanart_path": "",
        "logo_path": "",
        "favorite": 1,
        "last_played": None,
        "play_count": 0,
    },
    {
        "id": -202,
        "title": "Pokémon Emerald",
        "platform_id": "gba",
        "platform": "Game Boy Advance",
        "genres": "RPG",
        "release_year": 2004,
        "description": "Mock design item. Replace by scanning your library.",
        "rom_path": "mock://emerald",
        "emulator_profile_id": "mgba_gba",
        "cover_path": "DefaultProgram.png",
        "fanart_path": "",
        "logo_path": "",
        "favorite": 0,
        "last_played": None,
        "play_count": 0,
    },
    {
        "id": -301,
        "title": "Super Mario Galaxy",
        "platform_id": "wii",
        "platform": "Nintendo Wii",
        "genres": "Platformer",
        "release_year": 2007,
        "description": "Mock design item. Replace by scanning your library.",
        "rom_path": "mock://galaxy",
        "emulator_profile_id": "dolphin_wii",
        "cover_path": "DefaultProgram.png",
        "fanart_path": "",
        "logo_path": "",
        "favorite": 0,
        "last_played": None,
        "play_count": 0,
    },
]
